[project]
name = "upgrade-specification"
authors = ["Development Team"]
description = "Comprehensive asset tracking and verification system"
telemetry = false
requirements = []
[contracts.tracking-vault]
path = "contracts/tracking-vault.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
